name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Run build script
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Create Add-on Zip
        run: |
          zip -r plugin.video.skipintro-${{ env.NEW_VERSION }}.zip .

      - name: Update Repository XML
        run: |
          sed -i 's/version="[0-9.]*"/version="'${{ env.NEW_VERSION }}'"/g' release/repository.plugin.video.skipintro.xml
          sed -i 's/plugin\.video\.skipintro-[0-9.]*.zip/plugin.video.skipintro-'${{ env.NEW_VERSION }}'.zip/g' release/repository.plugin.video.skipintro.xml

      - name: Create Repository Zip
        run: |
          zip -r repository.plugin.video.skipintro.zip release/repository.plugin.video.skipintro.xml

      - name: Create Tag
        id: tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -a v${{ env.NEW_VERSION }} -m "Release v${{ env.NEW_VERSION }}"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
          
      - name: Verify Tag
        run: |
          git fetch --tags
          git tag --list

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: plugin.video.skipintro-${{ env.NEW_VERSION }}.zip
          tag_name: v${{ env.NEW_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move Release Files
        run: |
          mv plugin.video.skipintro-${{ env.NEW_VERSION }}.zip release/
          mv repository.plugin.video.skipintro.zip release/

      - name: Commit and Push Changes
        run: |
          git add release/plugin.video.skipintro-${{ env.NEW_VERSION }}.zip release/repository.plugin.video.skipintro.zip
          git commit -m "Update release files [skip ci]"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
          fi
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          
